// Scouter Server Go — plugin gRPC contract.
//
// This proto defines the wire contract between scouter-server and
// user-developed plugins. Plugins are external processes launched by
// hashicorp/go-plugin; they implement one or more of the services below.
//
// Stability: v1. Breaking changes require bumping the package name.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: internal/plugin/proto/plugin.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AlertPayload mirrors the subset of scouter AlertPack that is most useful
// for plugin authors. Tag values are flattened to strings; complex tag
// values (lists, maps) are JSON-encoded.
type AlertPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`   // epoch millis
	Level         uint32                 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"` // 0=info, 1=warn, 2=error, 3=fatal
	ObjType       string                 `protobuf:"bytes,3,opt,name=obj_type,json=objType,proto3" json:"obj_type,omitempty"`
	ObjHash       int32                  `protobuf:"varint,4,opt,name=obj_hash,json=objHash,proto3" json:"obj_hash,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertPayload) Reset() {
	*x = AlertPayload{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertPayload) ProtoMessage() {}

func (x *AlertPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertPayload.ProtoReflect.Descriptor instead.
func (*AlertPayload) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *AlertPayload) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *AlertPayload) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *AlertPayload) GetObjType() string {
	if x != nil {
		return x.ObjType
	}
	return ""
}

func (x *AlertPayload) GetObjHash() int32 {
	if x != nil {
		return x.ObjHash
	}
	return 0
}

func (x *AlertPayload) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AlertPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AlertPayload) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// CounterPayload mirrors scouter PerfCounterPack. Counter values are
// flattened to float64; non-numeric values are skipped.
type CounterPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"` // epoch millis
	ObjName       string                 `protobuf:"bytes,2,opt,name=obj_name,json=objName,proto3" json:"obj_name,omitempty"`
	TimeType      uint32                 `protobuf:"varint,3,opt,name=time_type,json=timeType,proto3" json:"time_type,omitempty"` // 1=Realtime, 2=FiveMin, 3=Hour, etc.
	Counters      map[string]float64     `protobuf:"bytes,4,rep,name=counters,proto3" json:"counters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterPayload) Reset() {
	*x = CounterPayload{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterPayload) ProtoMessage() {}

func (x *CounterPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterPayload.ProtoReflect.Descriptor instead.
func (*CounterPayload) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *CounterPayload) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *CounterPayload) GetObjName() string {
	if x != nil {
		return x.ObjName
	}
	return ""
}

func (x *CounterPayload) GetTimeType() uint32 {
	if x != nil {
		return x.TimeType
	}
	return 0
}

func (x *CounterPayload) GetCounters() map[string]float64 {
	if x != nil {
		return x.Counters
	}
	return nil
}

// Empty ack — plugins never mutate packs, they only observe.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{2}
}

var File_internal_plugin_proto_plugin_proto protoreflect.FileDescriptor

const file_internal_plugin_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\"internal/plugin/proto/plugin.proto\x12\x11scouter.plugin.v1\"\x96\x02\n" +
	"\fAlertPayload\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x14\n" +
	"\x05level\x18\x02 \x01(\rR\x05level\x12\x19\n" +
	"\bobj_type\x18\x03 \x01(\tR\aobjType\x12\x19\n" +
	"\bobj_hash\x18\x04 \x01(\x05R\aobjHash\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12=\n" +
	"\x04tags\x18\a \x03(\v2).scouter.plugin.v1.AlertPayload.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x0eCounterPayload\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x19\n" +
	"\bobj_name\x18\x02 \x01(\tR\aobjName\x12\x1b\n" +
	"\ttime_type\x18\x03 \x01(\rR\btimeType\x12K\n" +
	"\bcounters\x18\x04 \x03(\v2/.scouter.plugin.v1.CounterPayload.CountersEntryR\bcounters\x1a;\n" +
	"\rCountersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x05\n" +
	"\x03Ack2L\n" +
	"\x06IAlert\x12B\n" +
	"\aProcess\x12\x1f.scouter.plugin.v1.AlertPayload\x1a\x16.scouter.plugin.v1.Ack2P\n" +
	"\bICounter\x12D\n" +
	"\aProcess\x12!.scouter.plugin.v1.CounterPayload\x1a\x16.scouter.plugin.v1.AckBMZKgithub.com/scouter-project/scouter-server-go/internal/plugin/proto;pluginpbb\x06proto3"

var (
	file_internal_plugin_proto_plugin_proto_rawDescOnce sync.Once
	file_internal_plugin_proto_plugin_proto_rawDescData []byte
)

func file_internal_plugin_proto_plugin_proto_rawDescGZIP() []byte {
	file_internal_plugin_proto_plugin_proto_rawDescOnce.Do(func() {
		file_internal_plugin_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_plugin_proto_plugin_proto_rawDesc), len(file_internal_plugin_proto_plugin_proto_rawDesc)))
	})
	return file_internal_plugin_proto_plugin_proto_rawDescData
}

var file_internal_plugin_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_plugin_proto_plugin_proto_goTypes = []any{
	(*AlertPayload)(nil),   // 0: scouter.plugin.v1.AlertPayload
	(*CounterPayload)(nil), // 1: scouter.plugin.v1.CounterPayload
	(*Ack)(nil),            // 2: scouter.plugin.v1.Ack
	nil,                    // 3: scouter.plugin.v1.AlertPayload.TagsEntry
	nil,                    // 4: scouter.plugin.v1.CounterPayload.CountersEntry
}
var file_internal_plugin_proto_plugin_proto_depIdxs = []int32{
	3, // 0: scouter.plugin.v1.AlertPayload.tags:type_name -> scouter.plugin.v1.AlertPayload.TagsEntry
	4, // 1: scouter.plugin.v1.CounterPayload.counters:type_name -> scouter.plugin.v1.CounterPayload.CountersEntry
	0, // 2: scouter.plugin.v1.IAlert.Process:input_type -> scouter.plugin.v1.AlertPayload
	1, // 3: scouter.plugin.v1.ICounter.Process:input_type -> scouter.plugin.v1.CounterPayload
	2, // 4: scouter.plugin.v1.IAlert.Process:output_type -> scouter.plugin.v1.Ack
	2, // 5: scouter.plugin.v1.ICounter.Process:output_type -> scouter.plugin.v1.Ack
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_plugin_proto_plugin_proto_init() }
func file_internal_plugin_proto_plugin_proto_init() {
	if File_internal_plugin_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_plugin_proto_plugin_proto_rawDesc), len(file_internal_plugin_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_plugin_proto_plugin_proto_goTypes,
		DependencyIndexes: file_internal_plugin_proto_plugin_proto_depIdxs,
		MessageInfos:      file_internal_plugin_proto_plugin_proto_msgTypes,
	}.Build()
	File_internal_plugin_proto_plugin_proto = out.File
	file_internal_plugin_proto_plugin_proto_goTypes = nil
	file_internal_plugin_proto_plugin_proto_depIdxs = nil
}
