// Scouter Server Go — plugin gRPC contract.
//
// This proto defines the wire contract between scouter-server and
// user-developed plugins. Plugins are external processes launched by
// hashicorp/go-plugin; they implement one or more of the services below.
//
// Stability: v1. Breaking changes require bumping the package name.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.3
// source: internal/plugin/proto/plugin.proto

package pluginpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IAlert_Process_FullMethodName = "/scouter.plugin.v1.IAlert/Process"
)

// IAlertClient is the client API for IAlert service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IAlert — called once per AlertPack on scouter-server.
// Mirrors Java scouter.server.plugin.IAlert.
type IAlertClient interface {
	Process(ctx context.Context, in *AlertPayload, opts ...grpc.CallOption) (*Ack, error)
}

type iAlertClient struct {
	cc grpc.ClientConnInterface
}

func NewIAlertClient(cc grpc.ClientConnInterface) IAlertClient {
	return &iAlertClient{cc}
}

func (c *iAlertClient) Process(ctx context.Context, in *AlertPayload, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, IAlert_Process_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IAlertServer is the server API for IAlert service.
// All implementations must embed UnimplementedIAlertServer
// for forward compatibility.
//
// IAlert — called once per AlertPack on scouter-server.
// Mirrors Java scouter.server.plugin.IAlert.
type IAlertServer interface {
	Process(context.Context, *AlertPayload) (*Ack, error)
	mustEmbedUnimplementedIAlertServer()
}

// UnimplementedIAlertServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIAlertServer struct{}

func (UnimplementedIAlertServer) Process(context.Context, *AlertPayload) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedIAlertServer) mustEmbedUnimplementedIAlertServer() {}
func (UnimplementedIAlertServer) testEmbeddedByValue()                {}

// UnsafeIAlertServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IAlertServer will
// result in compilation errors.
type UnsafeIAlertServer interface {
	mustEmbedUnimplementedIAlertServer()
}

func RegisterIAlertServer(s grpc.ServiceRegistrar, srv IAlertServer) {
	// If the following call panics, it indicates UnimplementedIAlertServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IAlert_ServiceDesc, srv)
}

func _IAlert_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAlertServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAlert_Process_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAlertServer).Process(ctx, req.(*AlertPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// IAlert_ServiceDesc is the grpc.ServiceDesc for IAlert service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IAlert_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scouter.plugin.v1.IAlert",
	HandlerType: (*IAlertServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _IAlert_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/plugin/proto/plugin.proto",
}

const (
	ICounter_Process_FullMethodName = "/scouter.plugin.v1.ICounter/Process"
)

// ICounterClient is the client API for ICounter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ICounter — called once per PerfCounterPack on scouter-server.
// Mirrors Java scouter.server.plugin.ICounter.
type ICounterClient interface {
	Process(ctx context.Context, in *CounterPayload, opts ...grpc.CallOption) (*Ack, error)
}

type iCounterClient struct {
	cc grpc.ClientConnInterface
}

func NewICounterClient(cc grpc.ClientConnInterface) ICounterClient {
	return &iCounterClient{cc}
}

func (c *iCounterClient) Process(ctx context.Context, in *CounterPayload, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ICounter_Process_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ICounterServer is the server API for ICounter service.
// All implementations must embed UnimplementedICounterServer
// for forward compatibility.
//
// ICounter — called once per PerfCounterPack on scouter-server.
// Mirrors Java scouter.server.plugin.ICounter.
type ICounterServer interface {
	Process(context.Context, *CounterPayload) (*Ack, error)
	mustEmbedUnimplementedICounterServer()
}

// UnimplementedICounterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedICounterServer struct{}

func (UnimplementedICounterServer) Process(context.Context, *CounterPayload) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedICounterServer) mustEmbedUnimplementedICounterServer() {}
func (UnimplementedICounterServer) testEmbeddedByValue()                  {}

// UnsafeICounterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ICounterServer will
// result in compilation errors.
type UnsafeICounterServer interface {
	mustEmbedUnimplementedICounterServer()
}

func RegisterICounterServer(s grpc.ServiceRegistrar, srv ICounterServer) {
	// If the following call panics, it indicates UnimplementedICounterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ICounter_ServiceDesc, srv)
}

func _ICounter_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CounterPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ICounterServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ICounter_Process_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ICounterServer).Process(ctx, req.(*CounterPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// ICounter_ServiceDesc is the grpc.ServiceDesc for ICounter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ICounter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scouter.plugin.v1.ICounter",
	HandlerType: (*ICounterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _ICounter_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/plugin/proto/plugin.proto",
}
